### ISSUE TITLE
Segfault on Debian Bookworm

### ISSUE THREAD

**Issue by mr-berndt** [markmcconnell/mai#4]
When compiling on Debian Bookworm (testing), i get it to compile, when I disable -Werror in the Makefile but I end up with a segfault and nothing else. I suspect the libraries on Bookworm are newer that the ones mai is ment to compile against.

Is there any chance of updating the sources to compile on newer systems?

**Comment by markmcconnell** [comment]
Replicated issues.  Tested fixes.  Pushed update.  Enjoy!
