### ISSUE TITLE
[ERROR] mai_rtp_init could not open multicast socket

### ISSUE THREAD

**Issue by briggeml** [markmcconnell/mai#7]
Is there any way to get more information in debug mode? Right now it is unclear why a multicast socket is not created:

`sudo mai -i eth0 -m recv -a 239.1.4.1:3000 -s sess1 -b 16 -r 48000 -c 2 -p 1000 -v`

[DEBUG] mai_ptp_init         PTP Domain: 224.0.1.129 (0)
[ERROR] sock_recv            multicast address (239.1.4.1:3000): Success.
[ERROR] mai_rtp_init         could not open multicast socket

**Comment by markmcconnell** [comment]
There is a fair amount of debug information already.  This was a result of a bug in the args parsing code.  This has been fixed in the latest commit.
